name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: Example: macOS Big Sur 11.4
    validations:
      required: true
  - type: input
    attributes:
      label: Deno version
      description: What version of Deno are you using?
      placeholder: Example: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Nessie version
      description: What version of Nessie are you using?
      placeholder: Example: 2.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducing steps
      description: Describe the bug
      placeholder: |
        Steps to reproduce the behavior:

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Aditional information
      description: Add any aditional information you belive could help in fixing this issue
    validations:
      required: false
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
  - type: markdown
    attributes:
      value: "Thanks for using Nessie, and helping us to improve!"