blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/halvardssm/deno-nessie/discussions
    about: Please ask and answer questions here.
  - name: Chat
    url: https://discord.gg/8WXfG2tvfr
    about: Join our discord channel which we are sharing with DenoDB 