name: Publish Docker

env:
  DENO_VERSION: 1.10.2
  NESSIE_VERSION: 2.0.0-rc4
  LATEST_VERSION_STABLE: 1.3.2
  LATEST_VERSION_NEXT: 2.0.0-rc4

on:
  release:
    types: [published]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tags
        run: |
          IMAGE_TAGS=$(deno run helpers/get_image_tags.ts ${{ env.NESSIE_VERSION }} ${{ env.LATEST_VERSION_STABLE }} ${{ env.LATEST_VERSION_NEXT }})
          echo "IMAGE_TAGS=$IMAGE_TAGS"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./image/Dockerfile
          tags: ${{ env.IMAGE_TAGS }}
          build-args: |
            DENO_VERSION=${{ env.DENO_VERSION }}
