name: Publish Docker

env:
  DENO_VERSION: 1.10.2
  NESSIE_VERSION: 2.0.0-rc4

on:
  release:
    types: [published]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./image/Dockerfile
          tags: |
            halvardm/nessie:${{ env.NESSIE_VERSION }}
            halvardm/nessie:latest
          build-args: |
            DENO_VERSION=${{ env.DENO_VERSION }}
